---
#Add proxy server [apache]
- name: Insert file with blockinfile
  blockinfile:
    path: "{{ directory_for_ubuntu }}/{{ conf_file_name }}.conf"
    block: |
      
      <VirtualHost *:*>
      ServerName {{ server_name }}
      ProxyRequests           Off
      TraceEnable             off
      ProxyErrorOverride      On
      ProxyPreserveHost       On
      ProxyPass /.well-known !
      ProxyPass / http://{{ proxy_pass }}/ timeout=1200 Keepalive=On
      ProxyPassReverse / http://{{ proxy_pass }}/
      ProxyTimeout 1200

      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" detailed
      CustomLog /var/log/httpd/access_log detailed

      RewriteEngine on
      RewriteCond %{SERVER_NAME} ={{ server_name }}
      RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

      RequestHeader set "X-RP-UNIQUE-ID"     "%{UNIQUE_ID}e"
      RequestHeader set "X-RP-REMOTE-USER"   "%{REMOTE_USER}e"
      RequestHeader set "X-RP-SSL-PROTOCOL"  "%{SSL_PROTOCOL}s"
      RequestHeader set "X-RP-SSL-CIPHER"    "%{SSL_CIPHER}s"
      RequestHeader set X-Forwarded-Proto: "https"
      Header always set Strict-Transport-Security "max-age=63072000;"
      Header set X-Content-Type-Options "nosniff"
      Header always append X-Frame-Options "SAMEORIGIN"
      Header set Cache-Control "no-cache, no-store, no-transform"
      Header set Pragma "no-cache"
      Header set X-XSS-Protection "1;  mode=block"
      Header set Referrer-Policy: "strict-origin-when-cross-origin"
      Header set Content-Security-Policy: "default-src https: data: 'self' 'unsafe-inline' 'unsafe-eval';"
      Header set Feature-Policy: "fullscreen 'self'"
      Header set x-permitted-cross-domain-policies "none"



      </VirtualHost>


- name: Remove line
  lineinfile:
    path: "{{ directory_for_ubuntu }}/{{ conf_file_name }}.conf"
    regexp: "# BEGIN ANSIBLE MANAGED BLOCK"
    state: absent

- name: Remove line
  lineinfile:
    path: "{{ directory_for_ubuntu }}/{{ conf_file_name }}.conf"
    regexp: "# END ANSIBLE MANAGED BLOCK"
    state: absent
  notify: restart apache
