---
# tasks file for dns_playbook
#Add dns 
- name: Change date
  replace:
    path: "/var/named/{{ directory_forward }}.db"
    regexp: "{{ old_date }}"
    replace: "{{ new_date }}"

- name: Insert file with blockinfile [add dns A or CNAME zone]
  blockinfile:
    path: "/var/named/{{ directory_forward }}.db"
    block: |
      #$TTL 86400
      #@   IN  SOA {{ ansible_fqdn }}. root.{{ domain }}. (
              # any numerical values are OK for serial number but
              # recommendation is [YYYYMMDDnn] (update date + number)
      #        20200920  ;Serial
      #        3600      ;Refresh
      #        1800      ;Retry
      #        604800    ;Expire
      #        86400     ;Minimum TTL
      #)
              # define Name Server
      #        IN  NS    {{ ansible_fqdn }}.
              # define Name Server's IP address
      #        IN  A     192.168.0.46
              # define Mail Exchanger Server
      #        IN  MX 10  {{ ansible_fqdn }}.

              # define each IP address of a hostname
      #        ns      IN  A       192.168.0.46
      #        www     IN  A       192.168.0.46
      {{ sub_domain }}     IN  CNAME   {{ domain }}.


- name: Remove line
  lineinfile:
    path: "/var/named/{{ directory_forward }}.db"
    regexp: "# BEGIN ANSIBLE MANAGED BLOCK"
    state: absent

- name: Remove line
  lineinfile:
    path: "/var/named/{{ directory_forward }}.db"
    regexp: "# END ANSIBLE MANAGED BLOCK"
    state: absent


- name: Change date
  replace:
    path: "/var/named/{{ directory_ptr }}.db"
    regexp: "{{ old_date }}"
    replace: "{{ new_date }}"

- name: Add PTR
  blockinfile:
    path: "/var/named/{{ directory_ptr }}.db"
    block: |
      #$TTL 86400
      #@   IN  SOA     {{ ansible_fqdn }}. root.{{ domain }}. (
      #        20200920  ;Serial
      #        3600      ;Refresh
      #        1800      ;Retry
      #        604800    ;Expire
      #        86400     ;Minimum TTL
      #)
        # define Name Server
      #  IN  NS      {{ ansible_fqdn }}.

      # define each hostname of an IP address
      #77.74.54.22.in-addr.arpa   IN  PTR     {{ ansible_fqdn }}.
      77.74.54.84.in-addr.arpa   IN  PTR     {{ new_sub_domain}}.



- name: Remove line
  lineinfile:
    path: "/var/named/{{ directory_ptr }}.db"
    regexp: "# BEGIN ANSIBLE MANAGED BLOCK"
    state: absent

- name: Remove line
  lineinfile:
    path: "/var/named/{{ directory_ptr }}.db"
    regexp: "# END ANSIBLE MANAGED BLOCK"
    state: absent
  notify: 
    - reload rndc forward
    - reload rndc ptr
