---
# tasks file for nginx_playbook
#Add proxy server [nginx]
- name: Insert file with blockinfile
  blockinfile:
    path: "{{ directory }}/{{ conf_file_name }}.conf"
    block: |
    



- name: Remove line
  lineinfile:
    path: "{{ directory }}/{{ conf_file_name }}.conf"
    regexp: "# BEGIN ANSIBLE MANAGED BLOCK"
    state: absent

- name: Remove line
  lineinfile:
    path: "{{ directory }}/{{ conf_file_name }}.conf"
    regexp: "# END ANSIBLE MANAGED BLOCK"
    state: absent
  notify: restart nginx
