---
# tasks file for nginx_playbook
#Add proxy server [nginx]
- name: Insert file with blockinfile
  blockinfile:
    path: "{{ directory }}/{{ conf_file_name }}.conf"
    block: |
      server {
          listen 80;
          server_name example.com;
          return 301 https://example.com$request_uri;
      }

      server {
          listen 443 ssl;
          server_name example.com;

          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;

          ssl_certificate           "/etc/letsencrypt/path/*.crt";
          ssl_certificate_key       "/etc/letsencrypt/path/*.key";

          location / {
              proxy_pass http://192.168.1.0/;
              proxy_pass_request_headers on;
              proxy_set_header        X-Real-IP       $remote_addr;
              proxy_set_header        Host            example.com;
              proxy_redirect          off;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_connect_timeout 1200;
              proxy_send_timeout 1200;
              proxy_read_timeout 1200;
              client_max_body_size 100M;
              client_body_buffer_size 128k;
              proxy_buffer_size 4k;
              proxy_buffers 4 32k;
              proxy_busy_buffers_size 64k;
          }
      }
    



- name: Remove line
  lineinfile:
    path: "{{ directory }}/{{ conf_file_name }}.conf"
    regexp: "# BEGIN ANSIBLE MANAGED BLOCK"
    state: absent

- name: Remove line
  lineinfile:
    path: "{{ directory }}/{{ conf_file_name }}.conf"
    regexp: "# END ANSIBLE MANAGED BLOCK"
    state: absent
  notify: restart nginx
